### ISSUE TITLE
The Push Notification System handle for the registration is invalid

### ISSUE THREAD

**Issue by weihangChen** [Azure/azure-notificationhubs-dotnet#128]
I have the hub working using "sandbox", then I switch it to "production" mode, I see the client device gets a new registration handle id, but when I test send on azure, get the error 
"The Push Notification System handle for the registration is invalid", I was using the variable "testsend" in code to check the outcome object as well, but it does not really say much. 
When it is switched to "production" mode, azure hub forwards the message to the production apple push notificaiton server, and my local devices is using the correct endpoint, but use a development certificate. I am not sure what this means, does the devices need to have the app installed with appstore provision profile in order to receive a message from "production" channel?
So the only way for testing is through "testflight"?

Any help will be appreciated.
Marc

**Comment by stankovski** [comment]
Hello, please post you service-specific question with use Azure support - they should be able to help you. In general you have to sign your app with production certificate in order to use `production` endpoint. Using `development` certificate and `production` endpoint will result in the above error.
