### ISSUE TITLE
Deleting and re-creating the same hub and namespace does not reset metrics on the portal

### ISSUE THREAD

**Issue by petro2050** [Azure/azure-notificationhubs-dotnet#129]
I had a notification hub & namespace configured on Azure Portal. I had 5 active devices registered as shown on the portal widget. I deleted the hub and the namespace and recreated them with the same names. The active device count still showed 5 instead of 0, so it seems deleting and re-creating the same resource does not reset everything.

**Comment by marstr** [comment]
Howdy @petro2050. Are the previously registered devices still able to receive notifications, or is the portal reported number the only evidence of devices still being associated with the given namespace and hub?

**Comment by petro2050** [comment]
I haven't tested whether the devices still receive notifications or not. I assumed that the devices are unregistered after the old namespace/hub is deleted but the device count cache isn't updated immediately. Is the count computed daily?

**Comment by marstr** [comment]
Without getting too much into how our service works, it is fair to say that the count of associated devices shown on the portal isn't as robust as the actual devices associated with a namespace/hub.

Because there isn't a particular action item associated with this issue for us, I'm going to close it out. But thanks for checking about this!
