### ISSUE TITLE
GetRegistrationsBy* returns Gcm*Registration instead of Fcm

### ISSUE THREAD

**Issue by alex-zyl** [Azure/azure-notificationhubs-dotnet#23]
In V3, GcmRegistrationDescription is marked as obsolete, so the SDK takes care of returning the same registration type when creating new Fcm registration. 
However, when querying device registrations, Gcm*RegistrationDescription objects returned as REST responds with Gcm*RegistrationDescription content. 
Shouldn't the SDK fully switch to Fcm and explicitly convert Gcm to Fcm descriptions?

**Comment by igprya** [comment]
You're correct in that the SDK should fully switch to Fcm types and indeed there was a conversion missing in one of the internal methods, resulting in obsolete Gcm types being occasionally returned.

Thanks for reporting this, we hope to get a fix rolled out soon! 🙂

**Comment by igprya** [comment]
@alex-zyl Fixed in version 3.0.1.

**Comment by alex-zyl** [comment]
@igprya 
This is great! Thanks!

**Comment by alex-zyl** [comment]
@igprya  @stankovski 
Guys, do I need permissions to create new branch and open a PR? Was trying to push into remote branch, but got 403

**Comment by igprya** [comment]
@alex-zyl Yes, only the owners of the repository are able to alter branches. In order to introduce a change you first need to [fork the repository](https://help.github.com/articles/about-forks/) and implement desired changes in a new branch inside your own fork.

When your feature is ready, you'll have an option to create a pull request that will propose to merge a branch with a feature from your fork into the `master` branch of this repository.

For example, the pull request that fixed the bug you've reported (#25) actually merged a `fcm-support-readentities-fix` [branch from my fork](https://github.com/igprya/azure-notificationhubs-dotnet/tree/fcm-support-readentities-fix) into this repository's `master` branch.

Hope that helps!

**Comment by alex-zyl** [comment]
@igprya 
Thanks for the hint. PR created
